site_name: SimpleMVI
site_url: https://arttttt.github.io/SimpleMVI
edit_uri: ""
theme:
  icon:
    logo: material/library-outline
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy

repo_name: arttttt/SimpleMVI
repo_url: https://github.com/arttttt/SimpleMVI

# Copyright
copyright: Copyright &copy; 2025 Artem Bambalov aka arttttt

nav:
  - SimpleMVI:
    - Overview: index.md
    - Quick start: overview/quickstart.md
    - Configuration: overview/configuration.md
  - Store:
      - Overview: store/store.md
  - Actor:
      - Overview: actor/actor.md
  - Middleware:
      - Overview: middleware/middleware.md

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/android_insights
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Android_Insights

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true