// Generated by SimpleMVI KSP TCAFeatureProcessor
// Do not edit manually

import ComposableArchitecture
import Shared
import Foundation


// MARK: - TCA Dependency Registration
extension DependencyValues {
    var counterStore: CounterStore {
        get { self[CounterStoreKey.self] }
        set { self[CounterStoreKey.self] = newValue }
    }
}

private struct CounterStoreKey: DependencyKey {
    static let liveValue: CounterStore = {
        fatalError("CounterStore dependency not configured. Provide it via withDependencies.")
    }()
}

// MARK: - TCA Feature
@Reducer
struct CounterFeature {
    
    @ObservableState
    struct State: Equatable {
        var counter: Int
    }

    @CasePathable
    enum Action {
        case decrement
        case increment
        case reset

        case _stateUpdated(CounterStore.State)
        case _sideEffect(CounterStoreSideEffect)
    }

    @Dependency(\.counterStore) var store

    var body: some ReducerOf<Self> {
        Reduce { state, action in
            switch action {
            case .decrement:
                store.accept(intent: CounterStoreIntentDecrement())
                return .none
                
            case .increment:
                store.accept(intent: CounterStoreIntentIncrement())
                return .none
                
            case .reset:
                store.accept(intent: CounterStoreIntentReset())
                return .none
                
            case let ._stateUpdated(domain):
                state.apply(from: domain)
                return .none

            case let ._sideEffect(sideEffect):
                return .none
            }
        }
    }
}


// MARK: - StoreState → Feature.State Mapper
extension CounterFeature.State {
    mutating func apply(from domain: CounterStore.State) {
        self.counter = Int(domain.counter)
    }
}

// MARK: - Factory
extension CounterFeature {
    
    static func from(
        store: CounterStore,
        withDependencies configureDependencies: @escaping (inout DependencyValues) -> Void = { _ in }
    ) -> StoreOf<Self> {
        let lifecycle = _CounterStoreLifecycle(store: store)

        let tcaStore = Store(
            initialState: State(
                counter: Int(store.state.counter),
            )
        ) {
            CounterFeature()
        } withDependencies: { deps in
            deps.counterStore = store
            configureDependencies(&deps)
        }

        lifecycle.start { action in
            await tcaStore.send(action)
        }

        return tcaStore
    }
}

// MARK: - Equatable
extension CounterFeature.State {
    static func == (lhs: Self, rhs: Self) -> Bool {
        return lhs.counter == rhs.counter
    }
}

// MARK: - Lifecycle Token
final class _CounterStoreLifecycle {
    private let store: CounterStore
    private var observerTask: Task<Void, Never>?

    init(store: CounterStore) {
        self.store = store
        store.doInit()
    }

    func start(send: @escaping (CounterFeature.Action) async -> Void) {
        observerTask = Task {
            await withTaskGroup(of: Void.self) { group in
                group.addTask {
                    do {
                        for try await state in asAsyncThrowingStream(CStateFlow<CounterStore.State>(source: self.store.states)) {
                            await send(._stateUpdated(state))
                        }
                    } catch {}
                }

                group.addTask {
                    do {
                        for try await effect in asAsyncThrowingStream(CFlow<CounterStoreSideEffect>(source: self.store.sideEffects)) {
                            await send(._sideEffect(effect))
                        }
                    } catch {}
                }
            }
        }
    }

    deinit {
        observerTask?.cancel()
        store.destroy()
    }
}

